"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { ArrowLeft, ArrowRightLeft, CheckCircle2, Clock3, Factory, FilterX, PackageCheck, PackageMinus, Plus, Save, Search, Trash2, Truck, XCircle } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import { initialProductMaster, initialWarehouses, ProductMaster, PRODUCT_STORAGE_KEY, WarehouseRecord, WAREHOUSE_STORAGE_KEY } from "@/lib/product-master"

export type InventoryOperationKind = "transfer" | "transfer-order" | "variant" | "production" | "output"
type OperationLine = { id: string; productId: string; reference: string; name: string; unit: string; quantity: number; stock: number; targetProductId?: string }
type OperationRecord = { id: string; kind: InventoryOperationKind; number: string; date: string; detail: string; source: string; destination: string; responsible: string; status: string; lines: OperationLine[]; createdAt: string }

const config = {
  transfer: { title: "Traslado entre bodegas", prefix: "TB", icon: ArrowRightLeft, destination: true, target: false, appliesStock: false, status: "Enviado", help: "Registra la salida de la bodega origen y la recepción en la bodega destino." },
  "transfer-order": { title: "Orden de traslado entre bodegas", prefix: "OTB", icon: Truck, destination: true, target: false, appliesStock: false, status: "Pendiente", help: "Solicita y reserva mercancía; no modifica existencias hasta confirmar el traslado." },
  variant: { title: "Traslado entre variantes", prefix: "TV", icon: ArrowRightLeft, destination: false, target: true, appliesStock: false, status: "Pendiente", help: "Convierte existencias de una referencia en otra variante relacionada." },
  production: { title: "Orden de producción", prefix: "OP", icon: Factory, destination: false, target: true, appliesStock: false, status: "Pendiente", help: "Consume materiales y registra la entrada del producto terminado." },
  output: { title: "Salida de inventarios", prefix: "SI", icon: PackageMinus, destination: false, target: false, appliesStock: false, status: "Pendiente", help: "Registra consumos internos, bajas, obsequios u otras salidas autorizadas." },
} as const

export function InventoryOperationView({ kind }: { kind: InventoryOperationKind }) {
  const current = config[kind]; const Icon = current.icon
  const storageKey = `ferreia-inventory-operations-${kind}`
  const [products, setProducts] = useState(initialProductMaster); const [warehouses, setWarehouses] = useState(initialWarehouses); const [records, setRecords] = useState<OperationRecord[]>([])
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [detail, setDetail] = useState(""); const [source, setSource] = useState(initialWarehouses[0].name); const [destination, setDestination] = useState(initialWarehouses[1].name); const [responsible, setResponsible] = useState("")
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState(""); const [lines, setLines] = useState<OperationLine[]>([]); const [saved, setSaved] = useState(false); const [lastSavedNumber, setLastSavedNumber] = useState(""); const [error, setError] = useState("")
  useEffect(() => { const p = localStorage.getItem(PRODUCT_STORAGE_KEY); const w = localStorage.getItem(WAREHOUSE_STORAGE_KEY); const r = localStorage.getItem(storageKey); if (p) setProducts(JSON.parse(p)); if (w) { const data = JSON.parse(w) as WarehouseRecord[]; setWarehouses(data); setSource(data[0]?.name ?? ""); setDestination(data[1]?.name ?? "") } if (r) setRecords(JSON.parse(r)) }, [storageKey])
  const number = String(records.length + 1).padStart(8, "0")
  const displayNumber = saved ? lastSavedNumber : number
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return products.filter((item) => item.active && (!q || [item.reference, item.name, item.sku, item.brand].some((value) => value.toLowerCase().includes(q)))) }, [products, query])
  function addLine() { const product = products.find((item) => item.id === selected); if (!product) return; if (lines.some((line) => line.productId === product.id)) return; setLines([...lines, { id: `LINE-${Date.now()}`, productId: product.id, reference: product.reference, name: product.name, unit: product.unit, quantity: 1, stock: product.stock }]); setSelected(""); setQuery(""); setSaved(false) }
  function updateLine(id: string, patch: Partial<OperationLine>) { setLines(lines.map((line) => line.id === id ? { ...line, ...patch } : line)); setSaved(false) }
  function save() {
    setError("")
    if (!detail.trim() || !lines.length) { setError("Ingresa el detalle y al menos un artículo."); return }
    if (current.destination && source === destination) { setError("La bodega origen y destino deben ser diferentes."); return }
    if (lines.some((line) => line.quantity <= 0 || line.quantity > line.stock || (current.target && !line.targetProductId))) { setError("Verifica cantidades, existencias y artículos destino."); return }
    const record: OperationRecord = { id: `${current.prefix}-${Date.now()}`, kind, number, date, detail: detail.trim(), source, destination: current.destination ? destination : "", responsible, status: current.status, lines, createdAt: new Date().toISOString() }
    const nextRecords = [...records, record]; setLastSavedNumber(number); setRecords(nextRecords); localStorage.setItem(storageKey, JSON.stringify(nextRecords))
    if (current.appliesStock) { const nextProducts = products.map((product) => { const outgoing = lines.filter((line) => line.productId === product.id).reduce((sum, line) => sum + line.quantity, 0); const incoming = lines.filter((line) => line.targetProductId === product.id).reduce((sum, line) => sum + line.quantity, 0); return outgoing || incoming ? { ...product, stock: product.stock - outgoing + incoming } : product }); setProducts(nextProducts); localStorage.setItem(PRODUCT_STORAGE_KEY, JSON.stringify(nextProducts)) }
    setSaved(true)
  }
  function reset() { setDetail(""); setResponsible(""); setLines([]); setSaved(false); setError("") }
  function updateStatus(id: string, status: string) {
    const record = records.find((item) => item.id === id)
    const terminal = (kind === "variant" && status === "Confirmado") || (kind === "production" && status === "Terminada") || (kind === "output" && status === "Aplicada")
    if (record && terminal && !["Confirmado", "Terminada", "Aplicada"].includes(record.status)) applyStock(record)
    const next = records.map((item) => item.id === id ? { ...item, status } : item)
    setRecords(next); localStorage.setItem(storageKey, JSON.stringify(next))
  }
  function applyStock(record: OperationRecord) {
    const nextProducts = products.map((product) => {
      const outgoing = record.lines.filter((line) => line.productId === product.id).reduce((sum, line) => sum + line.quantity, 0)
      const incoming = record.lines.filter((line) => line.targetProductId === product.id).reduce((sum, line) => sum + line.quantity, 0)
      return outgoing || incoming ? { ...product, stock: product.stock - outgoing + incoming } : product
    })
    setProducts(nextProducts); localStorage.setItem(PRODUCT_STORAGE_KEY, JSON.stringify(nextProducts))
  }
  return <div className="space-y-5"><Button asChild variant="ghost" size="sm"><Link href="/admin/inventario"><ArrowLeft className="mr-2 h-4 w-4" />Volver a existencias</Link></Button>
    <div className="flex flex-col justify-between gap-3 sm:flex-row"><div className="flex gap-3"><span className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="h-6 w-6" /></span><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">{current.title}</h1><Badge variant="secondary" className="font-mono">{current.prefix}-{displayNumber}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{current.help}</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={reset}><Plus className="mr-2 h-4 w-4" />Nuevo</Button><Button onClick={save} disabled={saved}><Save className="mr-2 h-4 w-4" />{saved ? "Guardado" : "Guardar"}</Button></div></div>
    {saved && <Notice tone="success">Documento {current.prefix}-{displayNumber} guardado correctamente.</Notice>}{error && <Notice tone="error">{error}</Notice>}
    <Card><CardContent className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Fecha"><Input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></Field><Field label="Bodega origen"><WarehouseSelect value={source} setValue={setSource} warehouses={warehouses} /></Field>{current.destination && <Field label="Bodega destino"><WarehouseSelect value={destination} setValue={setDestination} warehouses={warehouses} /></Field>}<Field label="Responsable"><Input value={responsible} onChange={(event) => setResponsible(event.target.value)} placeholder="Nombre o usuario" /></Field><Field label="Detalle / motivo *" wide><Textarea value={detail} onChange={(event) => setDetail(event.target.value)} placeholder="Describe el motivo y la autorización de la operación" /></Field></CardContent></Card>
    <Card><CardContent className="p-4"><div className="grid gap-3 lg:grid-cols-[minmax(220px,.8fr)_minmax(300px,1.2fr)_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => { setQuery(event.target.value); setSelected("") }} placeholder="Buscar referencia, nombre, SKU o marca..." /></div><Select value={selected} onValueChange={(value) => value && setSelected(value)}><SelectTrigger><SelectValue placeholder={`Seleccionar entre ${filtered.length} resultado(s)`} /></SelectTrigger><SelectContent>{filtered.map((item) => <SelectItem key={item.id} value={item.id}>{item.reference} · {item.name} · Stock {item.stock}</SelectItem>)}</SelectContent></Select><Button onClick={addLine} disabled={!selected}><Plus className="mr-2 h-4 w-4" />Adicionar</Button></div></CardContent></Card>
    <Card className="overflow-hidden"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/40"><TableHead>Referencia</TableHead><TableHead>Artículo origen</TableHead><TableHead>Unidad</TableHead><TableHead className="w-32">Cantidad</TableHead><TableHead className="text-right">Disponible</TableHead>{current.target && <TableHead>Artículo destino / terminado</TableHead>}<TableHead /></TableRow></TableHeader><TableBody>{lines.map((line) => <TableRow key={line.id}><TableCell className="font-mono font-semibold">{line.reference}</TableCell><TableCell className="min-w-56 font-medium">{line.name}</TableCell><TableCell>{line.unit}</TableCell><TableCell><Input type="number" min="1" max={line.stock} value={line.quantity} onChange={(event) => updateLine(line.id, { quantity: Number(event.target.value) })} /></TableCell><TableCell className="text-right">{line.stock}</TableCell>{current.target && <TableCell className="min-w-72"><Select value={line.targetProductId ?? ""} onValueChange={(value) => value && updateLine(line.id, { targetProductId: value })}><SelectTrigger><SelectValue placeholder="Seleccionar artículo destino" /></SelectTrigger><SelectContent>{products.filter((item) => item.active && item.id !== line.productId).map((item) => <SelectItem key={item.id} value={item.id}>{item.reference} · {item.name}</SelectItem>)}</SelectContent></Select></TableCell>}<TableCell><Button variant="ghost" size="icon" onClick={() => setLines(lines.filter((item) => item.id !== line.id))}><Trash2 className="h-4 w-4" /></Button></TableCell></TableRow>)}{!lines.length && <TableRow><TableCell colSpan={current.target ? 7 : 6} className="h-44 text-center text-muted-foreground"><Search className="mx-auto mb-2 h-6 w-6" />Adiciona los artículos de la operación.</TableCell></TableRow>}</TableBody></Table></div><div className="flex justify-end border-t bg-muted/20 px-5 py-4"><span className="text-sm text-muted-foreground">Unidades totales: <b className="ml-2 text-lg text-foreground">{lines.reduce((sum, line) => sum + line.quantity, 0)}</b></span></div></Card>
    {kind === "transfer" && <TransferHistory records={records} updateStatus={updateStatus} />}
    {kind === "transfer-order" && <TransferOrderHistory records={records} updateStatus={updateStatus} />}
    {["variant", "production", "output"].includes(kind) && <InventoryDocumentHistory kind={kind} records={records} updateStatus={updateStatus} />}
  </div>
}

function TransferHistory({ records, updateStatus }: { records: OperationRecord[]; updateStatus: (id: string, status: string) => void }) {
  const filters = useHistoryFilters(records); const ordered = [...filters.filtered].reverse()
  return <section className="space-y-3"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-lg font-bold">Traslados realizados</h2><p className="text-sm text-muted-foreground">Seguimiento y gestión por parte de la bodega destino</p></div><div className="flex flex-wrap gap-2"><StatusCount label="Enviados" value={records.filter((item) => item.status === "Enviado").length} tone="sky" /><StatusCount label="Recibidos" value={records.filter((item) => item.status === "Recibido").length} tone="amber" /><StatusCount label="Finalizados" value={records.filter((item) => item.status === "Finalizado").length} tone="green" /></div></div>
    <HistoryFilterBar {...filters} statuses={["Enviado", "Recibido", "Finalizado", "Rechazado"]} />
    <Card className="overflow-hidden"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/40"><TableHead>Traslado</TableHead><TableHead>Fecha</TableHead><TableHead>Origen → destino</TableHead><TableHead>Detalle</TableHead><TableHead className="text-right">Artículos</TableHead><TableHead className="text-right">Unidades</TableHead><TableHead>Responsable</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Gestión</TableHead></TableRow></TableHeader><TableBody>{ordered.map((record) => <TableRow key={record.id}><TableCell className="font-mono font-semibold">TB-{record.number}</TableCell><TableCell>{record.date}</TableCell><TableCell><p className="font-medium">{record.source}</p><p className="text-xs text-muted-foreground">→ {record.destination}</p></TableCell><TableCell className="max-w-56 truncate">{record.detail}</TableCell><TableCell className="text-right">{record.lines.length}</TableCell><TableCell className="text-right font-semibold">{record.lines.reduce((sum, line) => sum + line.quantity, 0)}</TableCell><TableCell>{record.responsible || "—"}</TableCell><TableCell><StatusBadge status={record.status} /></TableCell><TableCell><div className="flex justify-end gap-1">{record.status === "Enviado" && <><Button size="sm" variant="outline" onClick={() => updateStatus(record.id, "Rechazado")}><XCircle className="mr-1 h-3.5 w-3.5" />Rechazar</Button><Button size="sm" onClick={() => updateStatus(record.id, "Recibido")}><PackageCheck className="mr-1 h-3.5 w-3.5" />Recibir</Button></>}{record.status === "Recibido" && <Button size="sm" onClick={() => updateStatus(record.id, "Finalizado")}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Finalizar</Button>}{["Finalizado", "Rechazado"].includes(record.status) && <span className="text-xs text-muted-foreground">Proceso cerrado</span>}</div></TableCell></TableRow>)}{!ordered.length && <TableRow><TableCell colSpan={9} className="h-40 text-center text-muted-foreground"><Truck className="mx-auto mb-2 h-7 w-7" />No hay traslados para los filtros aplicados.</TableCell></TableRow>}</TableBody></Table></div></Card>
  </section>
}

function TransferOrderHistory({ records, updateStatus }: { records: OperationRecord[]; updateStatus: (id: string, status: string) => void }) {
  const filters = useHistoryFilters(records); const ordered = [...filters.filtered].reverse()
  return <section className="space-y-3"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-lg font-bold">Órdenes de traslado</h2><p className="text-sm text-muted-foreground">Aprobación, preparación y despacho de solicitudes entre bodegas</p></div><div className="flex flex-wrap gap-2"><StatusCount label="Pendientes" value={records.filter((item) => item.status === "Pendiente").length} tone="amber" /><StatusCount label="En preparación" value={records.filter((item) => item.status === "En preparación").length} tone="sky" /><StatusCount label="Despachadas" value={records.filter((item) => item.status === "Despachada").length} tone="green" /></div></div>
    <HistoryFilterBar {...filters} statuses={["Pendiente", "Aprobada", "En preparación", "Lista para despacho", "Despachada", "Rechazada", "Cancelada"]} />
    <Card className="overflow-hidden"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/40"><TableHead>Orden</TableHead><TableHead>Fecha</TableHead><TableHead>Origen → destino</TableHead><TableHead>Detalle</TableHead><TableHead className="text-right">Referencias</TableHead><TableHead className="text-right">Unidades</TableHead><TableHead>Solicitante</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Gestión</TableHead></TableRow></TableHeader><TableBody>{ordered.map((record) => <TableRow key={record.id}><TableCell className="font-mono font-semibold">OTB-{record.number}</TableCell><TableCell>{record.date}</TableCell><TableCell><p className="font-medium">{record.source}</p><p className="text-xs text-muted-foreground">→ {record.destination}</p></TableCell><TableCell className="max-w-56 truncate">{record.detail}</TableCell><TableCell className="text-right">{record.lines.length}</TableCell><TableCell className="text-right font-semibold">{record.lines.reduce((sum, line) => sum + line.quantity, 0)}</TableCell><TableCell>{record.responsible || "—"}</TableCell><TableCell><OrderStatusBadge status={record.status} /></TableCell><TableCell><div className="flex justify-end gap-1">
      {record.status === "Pendiente" && <><Button size="sm" variant="outline" onClick={() => updateStatus(record.id, "Rechazada")}><XCircle className="mr-1 h-3.5 w-3.5" />Rechazar</Button><Button size="sm" onClick={() => updateStatus(record.id, "Aprobada")}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Aprobar</Button></>}
      {record.status === "Aprobada" && <><Button size="sm" variant="outline" onClick={() => updateStatus(record.id, "Cancelada")}>Cancelar</Button><Button size="sm" onClick={() => updateStatus(record.id, "En preparación")}><PackageCheck className="mr-1 h-3.5 w-3.5" />Preparar</Button></>}
      {record.status === "En preparación" && <Button size="sm" onClick={() => updateStatus(record.id, "Lista para despacho")}><PackageCheck className="mr-1 h-3.5 w-3.5" />Marcar lista</Button>}
      {record.status === "Lista para despacho" && <Button size="sm" onClick={() => updateStatus(record.id, "Despachada")}><Truck className="mr-1 h-3.5 w-3.5" />Despachar</Button>}
      {["Despachada", "Rechazada", "Cancelada"].includes(record.status) && <span className="text-xs text-muted-foreground">Proceso cerrado</span>}
    </div></TableCell></TableRow>)}{!ordered.length && <TableRow><TableCell colSpan={9} className="h-40 text-center text-muted-foreground"><Clock3 className="mx-auto mb-2 h-7 w-7" />No hay órdenes para los filtros aplicados.</TableCell></TableRow>}</TableBody></Table></div></Card>
  </section>
}

function InventoryDocumentHistory({ kind, records, updateStatus }: { kind: InventoryOperationKind; records: OperationRecord[]; updateStatus: (id: string, status: string) => void }) {
  const current = config[kind]; const filters = useHistoryFilters(records); const ordered = [...filters.filtered].reverse()
  const completedStatus = kind === "variant" ? "Confirmado" : kind === "production" ? "Terminada" : "Aplicada"
  return <section className="space-y-3"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-lg font-bold">Historial de {current.title.toLowerCase()}</h2><p className="text-sm text-muted-foreground">Consulta, aprobación y trazabilidad de los documentos registrados</p></div><div className="flex gap-2"><StatusCount label="Pendientes" value={records.filter((item) => item.status === "Pendiente").length} tone="amber" /><StatusCount label="En proceso" value={records.filter((item) => ["Aprobada", "En proceso"].includes(item.status)).length} tone="sky" /><StatusCount label="Finalizados" value={records.filter((item) => item.status === completedStatus).length} tone="green" /></div></div>
    <HistoryFilterBar {...filters} statuses={kind === "production" ? ["Pendiente", "En proceso", "Terminada", "Cancelado"] : kind === "output" ? ["Pendiente", "Aprobada", "Aplicada", "Rechazado"] : ["Pendiente", "Confirmado", "Cancelado"]} />
    <Card className="overflow-hidden"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/40"><TableHead>Documento</TableHead><TableHead>Fecha</TableHead><TableHead>Bodega</TableHead><TableHead>Detalle</TableHead><TableHead className="text-right">Referencias</TableHead><TableHead className="text-right">Unidades</TableHead><TableHead>Responsable</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Gestión</TableHead></TableRow></TableHeader><TableBody>{ordered.map((record) => <TableRow key={record.id}><TableCell className="font-mono font-semibold">{current.prefix}-{record.number}</TableCell><TableCell>{record.date}</TableCell><TableCell>{record.source}</TableCell><TableCell className="max-w-64 truncate">{record.detail}</TableCell><TableCell className="text-right">{record.lines.length}</TableCell><TableCell className="text-right font-semibold">{record.lines.reduce((sum, line) => sum + line.quantity, 0)}</TableCell><TableCell>{record.responsible || "—"}</TableCell><TableCell><GenericStatusBadge status={record.status} /></TableCell><TableCell><div className="flex justify-end gap-1"><DocumentActions kind={kind} record={record} updateStatus={updateStatus} /></div></TableCell></TableRow>)}{!ordered.length && <TableRow><TableCell colSpan={9} className="h-40 text-center text-muted-foreground"><Clock3 className="mx-auto mb-2 h-7 w-7" />No hay documentos para los filtros aplicados.</TableCell></TableRow>}</TableBody></Table></div></Card>
  </section>
}

function DocumentActions({ kind, record, updateStatus }: { kind: InventoryOperationKind; record: OperationRecord; updateStatus: (id: string, status: string) => void }) {
  if (["Cancelado", "Rechazado", "Confirmado", "Terminada", "Aplicada"].includes(record.status)) return <span className="text-xs text-muted-foreground">Proceso cerrado</span>
  if (kind === "variant" && record.status === "Pendiente") return <><Button size="sm" variant="outline" onClick={() => updateStatus(record.id, "Cancelado")}>Cancelar</Button><Button size="sm" onClick={() => updateStatus(record.id, "Confirmado")}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Confirmar</Button></>
  if (kind === "production") {
    if (record.status === "Pendiente") return <><Button size="sm" variant="outline" onClick={() => updateStatus(record.id, "Cancelado")}>Cancelar</Button><Button size="sm" onClick={() => updateStatus(record.id, "En proceso")}><Factory className="mr-1 h-3.5 w-3.5" />Iniciar</Button></>
    if (record.status === "En proceso") return <Button size="sm" onClick={() => updateStatus(record.id, "Terminada")}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Terminar</Button>
  }
  if (kind === "output" && record.status === "Pendiente") return <><Button size="sm" variant="outline" onClick={() => updateStatus(record.id, "Rechazado")}>Rechazar</Button><Button size="sm" onClick={() => updateStatus(record.id, "Aprobada")}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Aprobar</Button></>
  if (kind === "output" && record.status === "Aprobada") return <Button size="sm" onClick={() => updateStatus(record.id, "Aplicada")}><PackageMinus className="mr-1 h-3.5 w-3.5" />Aplicar salida</Button>
  return null
}

function StatusBadge({ status }: { status: string }) { const styles: Record<string, string> = { Enviado: "bg-sky-50 text-sky-700", Recibido: "bg-amber-50 text-amber-700", Finalizado: "bg-emerald-50 text-emerald-700", Rechazado: "bg-rose-50 text-rose-700" }; return <Badge variant="secondary" className={styles[status] ?? ""}>{status}</Badge> }
function OrderStatusBadge({ status }: { status: string }) { const styles: Record<string, string> = { Pendiente: "bg-amber-50 text-amber-700", Aprobada: "bg-cyan-50 text-cyan-700", "En preparación": "bg-sky-50 text-sky-700", "Lista para despacho": "bg-violet-50 text-violet-700", Despachada: "bg-emerald-50 text-emerald-700", Rechazada: "bg-rose-50 text-rose-700", Cancelada: "bg-slate-100 text-slate-600" }; return <Badge variant="secondary" className={styles[status] ?? ""}>{status}</Badge> }
function GenericStatusBadge({ status }: { status: string }) { const styles: Record<string, string> = { Pendiente: "bg-amber-50 text-amber-700", Aprobada: "bg-cyan-50 text-cyan-700", "En proceso": "bg-sky-50 text-sky-700", Confirmado: "bg-emerald-50 text-emerald-700", Terminada: "bg-emerald-50 text-emerald-700", Aplicada: "bg-emerald-50 text-emerald-700", Rechazado: "bg-rose-50 text-rose-700", Cancelado: "bg-slate-100 text-slate-600" }; return <Badge variant="secondary" className={styles[status] ?? ""}>{status}</Badge> }
function StatusCount({ label, value, tone }: { label: string; value: number; tone: "sky" | "amber" | "green" }) { const styles = { sky: "bg-sky-50 text-sky-700", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700" }; return <span className={`rounded-lg px-3 py-1.5 text-xs font-medium ${styles[tone]}`}>{label}: <b>{value}</b></span> }

function useHistoryFilters<T extends { number: string; date: string; detail: string; status: string; responsible?: string; source?: string; destination?: string }>(records: T[]) {
  const [historyQuery, setHistoryQuery] = useState(""); const [historyStatus, setHistoryStatus] = useState("todos"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("")
  const filtered = useMemo(() => { const query = historyQuery.trim().toLowerCase(); return records.filter((record) => (!query || [record.number, record.detail, record.responsible ?? "", record.source ?? "", record.destination ?? ""].some((value) => value.toLowerCase().includes(query))) && (historyStatus === "todos" || record.status === historyStatus) && (!dateFrom || record.date >= dateFrom) && (!dateTo || record.date <= dateTo)) }, [records, historyQuery, historyStatus, dateFrom, dateTo])
  function resetHistoryFilters() { setHistoryQuery(""); setHistoryStatus("todos"); setDateFrom(""); setDateTo("") }
  return { filtered, historyQuery, setHistoryQuery, historyStatus, setHistoryStatus, dateFrom, setDateFrom, dateTo, setDateTo, resetHistoryFilters }
}

function HistoryFilterBar({ historyQuery, setHistoryQuery, historyStatus, setHistoryStatus, dateFrom, setDateFrom, dateTo, setDateTo, resetHistoryFilters, statuses }: ReturnType<typeof useHistoryFilters<OperationRecord>> & { statuses: string[] }) {
  return <Card><CardContent className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_190px_150px_150px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={historyQuery} onChange={(event) => setHistoryQuery(event.target.value)} placeholder="Buscar documento, detalle, responsable o bodega..." /></div><Select value={historyStatus} onValueChange={(value) => value && setHistoryStatus(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todos">Todos los estados</SelectItem>{statuses.map((status) => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select><Input aria-label="Fecha inicial" type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} /><Input aria-label="Fecha final" type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} /><Button variant="outline" onClick={resetHistoryFilters} title="Limpiar filtros"><FilterX className="h-4 w-4" /></Button></CardContent></Card>
}

function WarehouseSelect({ value, setValue, warehouses }: { value: string; setValue: (value: string) => void; warehouses: WarehouseRecord[] }) { return <Select value={value} onValueChange={(next) => next && setValue(next)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{warehouses.filter((item) => item.active).map((item) => <SelectItem key={item.id} value={item.name}>{item.name}</SelectItem>)}</SelectContent></Select> }
function Field({ label, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { return <div className={`space-y-1.5 ${wide ? "md:col-span-2" : ""}`}><Label>{label}</Label>{children}</div> }
function Notice({ children, tone }: { children: React.ReactNode; tone: "success" | "error" }) { return <div className={`flex items-center gap-2 rounded-lg px-4 py-3 text-sm ${tone === "success" ? "bg-emerald-50 text-emerald-800" : "bg-rose-50 text-rose-800"}`}><CheckCircle2 className="h-4 w-4" />{children}</div> }
