"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { AlertTriangle, ArrowLeft, ArrowRight, Bell, CheckCircle2, Clock3, FilterX, ListFilter, Moon, Plus, Search, Sun, Warehouse, X } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { getWmsModule, WMS_KPIS, WMS_MODULES, WmsModuleDefinition } from "@/lib/wms-modules"
import { useWmsStore, WmsPriority, WmsTask } from "@/stores/wms-store"

const throughput = [{ hour:"06",inbound:18,outbound:8 },{ hour:"08",inbound:34,outbound:20 },{ hour:"10",inbound:52,outbound:38 },{ hour:"12",inbound:42,outbound:49 },{ hour:"14",inbound:66,outbound:58 },{ hour:"16",inbound:71,outbound:64 },{ hour:"18",inbound:38,outbound:70 }]
const tone: Record<string,string> = { Crítica:"bg-rose-50 text-rose-700 dark:bg-rose-950/50 dark:text-rose-300", Alta:"bg-orange-50 text-orange-700 dark:bg-orange-950/50 dark:text-orange-300", Media:"bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300", Baja:"bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300" }

function useTheme() { const darkMode=useWmsStore((state)=>state.darkMode); const setDarkMode=useWmsStore((state)=>state.setDarkMode); useEffect(()=>{ void useWmsStore.persist.rehydrate() },[]); useEffect(()=>{ document.documentElement.classList.toggle("dark",darkMode); document.documentElement.classList.toggle("light",!darkMode) },[darkMode]); return { darkMode,setDarkMode } }
function WmsTopbar({ title, description, back }: { title:string; description:string; back?:boolean }) { const {darkMode,setDarkMode}=useTheme(); return <div className="flex flex-col justify-between gap-3 border-b border-border pb-5 sm:flex-row sm:items-center"><div>{back && <Button asChild variant="ghost" size="sm" className="mb-2 -ml-2"><Link href="/admin/logistica"><ArrowLeft className="mr-2 h-4 w-4" />Dashboard WMS</Link></Button>}<div className="flex items-center gap-3"><span className="rounded-xl bg-primary p-2.5 text-primary-foreground"><Warehouse className="h-5 w-5" /></span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black tracking-tight">{title}</h1><Badge variant="outline" className="border-emerald-300 bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300">Operación en línea</Badge></div><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div></div><div className="flex items-center gap-2"><Button size="icon" variant="outline" title="Notificaciones"><Bell className="h-4 w-4" /></Button><Button size="icon" variant="outline" onClick={()=>setDarkMode(!darkMode)} title="Cambiar tema">{darkMode?<Sun className="h-4 w-4"/>:<Moon className="h-4 w-4"/>}</Button><div className="hidden rounded-lg border bg-card px-3 py-2 text-xs sm:block"><b>Turno A</b><span className="ml-2 text-muted-foreground">08 Ago · 08:42</span></div></div></div> }

export function WmsDashboard() { const tasks=useWmsStore((state)=>state.tasks); const warehouses=useWmsStore((state)=>state.warehouses); const events=useWmsStore((state)=>state.events); const pending=tasks.filter((task)=>task.progress<100).sort((a,b)=>priorityOrder(a.priority)-priorityOrder(b.priority)).slice(0,6); return <div className="space-y-6"><WmsTopbar title="Centro de control WMS" description="Visibilidad integral de inventario, tareas, capacidad y nivel de servicio." />
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{WMS_KPIS.map(({label,value,change,icon:Icon})=><Card key={label}><CardContent className="flex items-center gap-4 p-4"><span className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="h-5 w-5" /></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-black">{value}</p><p className="text-[11px] font-medium text-emerald-600">{change}</p></div></CardContent></Card>)}</div>
  <div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Flujo de unidades por hora</h2><p className="text-xs text-muted-foreground">Entradas y salidas procesadas hoy</p></div><Badge variant="secondary">Tiempo real</Badge></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={throughput}><defs><linearGradient id="inbound" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#4bbdbd" stopOpacity={.35}/><stop offset="95%" stopColor="#4bbdbd" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="hour" tickLine={false}/><YAxis tickLine={false}/><Tooltip/><Area type="monotone" dataKey="inbound" name="Entradas" stroke="#4bbdbd" strokeWidth={2} fill="url(#inbound)"/><Area type="monotone" dataKey="outbound" name="Salidas" stroke="#153947" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-bold">Capacidad de bodegas</h2><p className="mb-4 text-xs text-muted-foreground">Posiciones ocupadas por instalación</p><div className="space-y-5">{warehouses.map((warehouse)=>{const percent=Math.round(warehouse.occupied/warehouse.capacity*100);return <div key={warehouse.id}><div className="mb-2 flex justify-between text-sm"><span><b>{warehouse.name}</b><small className="ml-2 text-muted-foreground">{warehouse.city}</small></span><b className={percent>80?"text-amber-600":""}>{percent}%</b></div><Progress value={percent}/><p className="mt-1 text-[11px] text-muted-foreground">{warehouse.occupied.toLocaleString("es-CO")} de {warehouse.capacity.toLocaleString("es-CO")} posiciones</p></div>})}</div></CardContent></Card></div>
  <section><div className="mb-3"><h2 className="text-lg font-black">Operaciones WMS</h2><p className="text-sm text-muted-foreground">Acceso por proceso operativo</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{WMS_MODULES.map((module)=>{const Icon=module.icon;const active=tasks.filter((task)=>task.module===module.key&&task.progress<100).length;return <Link href={`/admin/logistica/${module.key}`} key={module.key} className="group rounded-xl border bg-card p-4 transition-all hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-lg"><div className="flex items-start justify-between"><span className="rounded-lg bg-primary/10 p-2.5 text-primary"><Icon className="h-5 w-5"/></span><Badge variant="secondary">{active} activas</Badge></div><h3 className="mt-4 font-bold">{module.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{module.description}</p><span className="mt-4 flex items-center text-xs font-bold text-primary">Abrir operación <ArrowRight className="ml-1 h-3.5 w-3.5 transition-transform group-hover:translate-x-1"/></span></Link>})}</div></section>
  <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card><CardContent className="p-5"><div className="mb-4 flex justify-between"><div><h2 className="font-bold">Cola operativa prioritaria</h2><p className="text-xs text-muted-foreground">Tareas que requieren atención del turno</p></div><ListFilter className="h-5 w-5 text-muted-foreground"/></div><TaskTable tasks={pending}/></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-bold">Actividad reciente</h2><div className="mt-4 space-y-4">{events.map((event)=><div key={event.id} className="flex gap-3"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${event.tone==="success"?"bg-emerald-500":event.tone==="warning"?"bg-amber-500":"bg-sky-500"}`}/><div><p className="text-sm font-semibold">{event.title}</p><p className="text-xs text-muted-foreground">{event.detail}</p><p className="mt-1 text-[10px] text-muted-foreground">{event.time}</p></div></div>)}</div></CardContent></Card></div>
  </div> }

export function WmsModuleView({ moduleKey }: { moduleKey:string }) { const module=getWmsModule(moduleKey)!; const tasks=useWmsStore((state)=>state.tasks); const addTask=useWmsStore((state)=>state.addTask); const updateTaskStatus=useWmsStore((state)=>state.updateTaskStatus); const moduleTasks=tasks.filter((task)=>task.module===module.key); const [query,setQuery]=useState(""); const [status,setStatus]=useState("todos"); const [priority,setPriority]=useState("todas"); const [view,setView]=useState("table"); const [createOpen,setCreateOpen]=useState(false); const [selected,setSelected]=useState<WmsTask|null>(null); const filtered=useMemo(()=>moduleTasks.filter((task)=>{const q=query.trim().toLowerCase();return (!q||[task.number,task.title,task.reference,task.owner,task.zone].some((value)=>value.toLowerCase().includes(q)))&&(status==="todos"||task.status===status)&&(priority==="todas"||task.priority===priority)}),[moduleTasks,query,status,priority]); const Icon=module.icon; const completed=moduleTasks.filter((task)=>task.progress===100).length; const exceptions=moduleTasks.filter((task)=>task.priority==="Crítica"||task.status.toLowerCase().includes("novedad")||task.status.toLowerCase().includes("bloqueada")).length; function advance(task:WmsTask){const index=module.stages.indexOf(task.status);const next=module.stages[Math.min(index+1,module.stages.length-1)];updateTaskStatus(task.id,next,next===module.stages[module.stages.length-1]?100:Math.min(task.progress+30,90));setSelected(null)} return <div className="space-y-5"><WmsTopbar title={module.name} description={module.description} back/>
  <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="h-6 w-6"/></span><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Operación WMS</p><p className="font-bold">CEDI Principal · Turno A</p></div></div><Button onClick={()=>setCreateOpen(true)}><Plus className="mr-2 h-4 w-4"/>{module.primaryAction}</Button></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniMetric label="Tareas activas" value={moduleTasks.length-completed} icon={Clock3}/><MiniMetric label="Completadas" value={completed} icon={CheckCircle2}/><MiniMetric label="Unidades" value={moduleTasks.reduce((sum,task)=>sum+task.units,0)} icon={Warehouse}/><MiniMetric label="Excepciones" value={exceptions} icon={AlertTriangle} warning={exceptions>0}/></div>
  <Card><CardContent className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-[1fr_190px_170px_auto_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar tarea, referencia, ubicación o responsable..."/></div><WmsSelect value={status} setValue={setStatus} options={["todos",...module.stages]} allLabel="Todos los estados"/><WmsSelect value={priority} setValue={setPriority} options={["todas","Crítica","Alta","Media","Baja"]} allLabel="Todas las prioridades"/><Button variant="outline" onClick={()=>{setQuery("");setStatus("todos");setPriority("todas")}}><FilterX className="h-4 w-4"/></Button><WmsSelect value={view} setValue={setView} options={["table","board"]} labels={{table:"Vista tabla",board:"Vista tablero"}}/></CardContent></Card>
  <Tabs value={view} onValueChange={setView}><TabsList className="hidden"><TabsTrigger value="table">Tabla</TabsTrigger><TabsTrigger value="board">Tablero</TabsTrigger></TabsList><TabsContent value="table"><Card><TaskTable tasks={filtered} onSelect={setSelected}/></Card></TabsContent><TabsContent value="board"><div className="grid gap-3 lg:grid-cols-3 2xl:grid-cols-5">{module.stages.map((stage)=><div key={stage} className="rounded-xl border bg-muted/30 p-3"><div className="mb-3 flex justify-between"><b className="text-xs">{stage}</b><Badge variant="secondary">{filtered.filter((task)=>task.status===stage).length}</Badge></div><div className="space-y-2">{filtered.filter((task)=>task.status===stage).map((task)=><button key={task.id} onClick={()=>setSelected(task)} className="w-full rounded-lg border bg-card p-3 text-left shadow-sm hover:border-primary/40"><div className="flex justify-between"><span className="font-mono text-xs font-bold">{task.number}</span><Badge className={tone[task.priority]} variant="secondary">{task.priority}</Badge></div><p className="mt-2 text-sm font-semibold">{task.title}</p><p className="mt-1 text-xs text-muted-foreground">{task.reference} · {task.zone}</p><Progress className="mt-3" value={task.progress}/></button>)}</div></div>)}</div></TabsContent></Tabs>
  {createOpen&&<CreateTaskModal module={module} close={()=>setCreateOpen(false)} create={()=>{addTask(module.key,module.stages[0]);setCreateOpen(false)}}/>}{selected&&<TaskDrawer task={selected} stages={module.stages} close={()=>setSelected(null)} advance={()=>advance(selected)}/>}</div> }

function TaskTable({ tasks,onSelect }: { tasks:WmsTask[];onSelect?:(task:WmsTask)=>void }) { return <Table><TableHeader><TableRow><TableHead>Tarea</TableHead><TableHead>Documento / referencia</TableHead><TableHead>Bodega / ubicación</TableHead><TableHead>Responsable</TableHead><TableHead>Prioridad</TableHead><TableHead>Estado</TableHead><TableHead className="w-40">Avance</TableHead><TableHead>Vence</TableHead></TableRow></TableHeader><TableBody>{tasks.map((task)=><TableRow key={task.id} onClick={()=>onSelect?.(task)} className={onSelect?"cursor-pointer":""}><TableCell><p className="font-mono text-xs font-bold">{task.number}</p><p className="text-xs text-muted-foreground">{task.title}</p></TableCell><TableCell>{task.reference}</TableCell><TableCell><p>{task.warehouse}</p><p className="text-xs text-muted-foreground">{task.zone}</p></TableCell><TableCell>{task.owner}</TableCell><TableCell><Badge className={tone[task.priority]} variant="secondary">{task.priority}</Badge></TableCell><TableCell><Badge variant="outline">{task.status}</Badge></TableCell><TableCell><div className="flex items-center gap-2"><Progress value={task.progress}/><span className="text-xs">{task.progress}%</span></div></TableCell><TableCell className="font-mono text-xs">{task.due}</TableCell></TableRow>)}{!tasks.length&&<TableRow><TableCell colSpan={8} className="h-40 text-center text-muted-foreground">No hay tareas para los filtros aplicados.</TableCell></TableRow>}</TableBody></Table> }
function MiniMetric({label,value,icon:Icon,warning}:{label:string;value:number;icon:typeof Clock3;warning?:boolean}){return <Card><CardContent className="flex items-center gap-3 p-4"><span className={`rounded-lg p-2 ${warning?"bg-amber-50 text-amber-700":"bg-primary/10 text-primary"}`}><Icon className="h-5 w-5"/></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-black">{value.toLocaleString("es-CO")}</p></div></CardContent></Card>}
function WmsSelect({value,setValue,options,allLabel,labels}:{value:string;setValue:(value:string)=>void;options:string[];allLabel?:string;labels?:Record<string,string>}){return <Select value={value} onValueChange={(next)=>next&&setValue(next)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map((option)=><SelectItem key={option} value={option}>{labels?.[option]??(["todos","todas"].includes(option)?allLabel:option)}</SelectItem>)}</SelectContent></Select>}
function CreateTaskModal({module,close,create}:{module:WmsModuleDefinition;close:()=>void;create:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm"><Card className="w-full max-w-2xl"><div className="flex justify-between border-b p-4"><div><h2 className="font-bold">{module.primaryAction}</h2><p className="text-xs text-muted-foreground">Registro simulado para el flujo {module.name.toLowerCase()}.</p></div><Button size="icon" variant="ghost" onClick={close}><X className="h-4 w-4"/></Button></div><CardContent className="grid gap-4 p-5 md:grid-cols-2"><Field label="Documento origen"><Input placeholder="OC, pedido, ASN o referencia"/></Field><Field label="Prioridad"><WmsSelect value="Media" setValue={()=>{}} options={["Crítica","Alta","Media","Baja"]}/></Field><Field label="Bodega"><WmsSelect value="CEDI Principal" setValue={()=>{}} options={["CEDI Principal","Bodega Norte","Bodega Sur"]}/></Field><Field label="Zona / ubicación"><Input placeholder="Ej. REC-01 o R03-N02-P04"/></Field><Field label="Responsable"><Input placeholder="Usuario o equipo operativo"/></Field><Field label="Fecha requerida"><Input type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><div className="flex justify-end gap-2 md:col-span-2"><Button variant="outline" onClick={close}>Cancelar</Button><Button onClick={create}><Plus className="mr-2 h-4 w-4"/>Crear tarea</Button></div></CardContent></Card></div>}
function TaskDrawer({task,stages,close,advance}:{task:WmsTask;stages:string[];close:()=>void;advance:()=>void}){const last=task.status===stages[stages.length-1];return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40 backdrop-blur-sm"><div className="h-full w-full max-w-lg overflow-y-auto border-l bg-background p-5 shadow-2xl"><div className="flex justify-between"><div><Badge className={tone[task.priority]} variant="secondary">{task.priority}</Badge><h2 className="mt-2 text-xl font-black">{task.title}</h2><p className="font-mono text-sm text-muted-foreground">{task.number}</p></div><Button size="icon" variant="ghost" onClick={close}><X className="h-4 w-4"/></Button></div><div className="mt-6 grid grid-cols-2 gap-3">{[["Referencia",task.reference],["Responsable",task.owner],["Bodega",task.warehouse],["Ubicación",task.zone],["Unidades",String(task.units)],["Vencimiento",task.due]].map(([label,value])=><div key={label} className="rounded-lg border p-3"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>)}</div><div className="mt-6"><div className="mb-2 flex justify-between text-sm"><b>Avance operativo</b><span>{task.progress}%</span></div><Progress value={task.progress}/></div><div className="mt-6"><h3 className="font-bold">Flujo de estados</h3><div className="mt-3 space-y-2">{stages.map((stage,index)=>{const current=stage===task.status;const done=index<stages.indexOf(task.status);return <div key={stage} className={`flex items-center gap-3 rounded-lg border p-3 ${current?"border-primary bg-primary/5":""}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${done?"bg-emerald-500 text-white":current?"bg-primary text-primary-foreground":"bg-muted"}`}>{done?<CheckCircle2 className="h-4 w-4"/>:index+1}</span><span className="text-sm font-medium">{stage}</span>{current&&<Badge className="ml-auto">Actual</Badge>}</div>})}</div></div><div className="sticky bottom-0 mt-8 flex gap-2 border-t bg-background pt-4"><Button className="flex-1" onClick={advance} disabled={last}>{last?"Proceso completado":"Avanzar al siguiente estado"}</Button><Button variant="outline" onClick={close}>Cerrar</Button></div></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function priorityOrder(priority:WmsPriority){return {Crítica:0,Alta:1,Media:2,Baja:3}[priority]}
