import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeft, CheckCircle2, CircleDollarSign, FileCheck2, Landmark, PackageCheck, Settings2, ShieldCheck, Users } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { getMovementModule, MOVEMENT_MODULES } from "@/lib/movement-modules"
import { InventoryNoteView } from "@/components/admin/inventory-note-view"
import { ElectronicBillingView, ElectronicDocumentKind } from "@/components/admin/electronic-billing-view"
import { QuotationView } from "@/components/admin/quotation-view"

export function generateStaticParams() { return MOVEMENT_MODULES.map((item) => ({ slug: item.slug })) }

export default async function MovementModulePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const module = getMovementModule(slug); if (!module) notFound()
  if (slug === "nota-inventarios") return <InventoryNoteView />
  if (slug === "cotizacion") return <QuotationView />
  const electronicDocuments: Record<string, ElectronicDocumentKind> = { "facturacion-pos": "pos", "factura-venta": "invoice", "devolucion-pos": "pos-return", "devolucion-factura-electronica": "invoice-return", "nota-credito-facturacion": "credit-note", "nota-debito-facturacion": "debit-note" }
  if (electronicDocuments[slug]) return <ElectronicBillingView kind={electronicDocuments[slug]} />
  const dianRequirements = module.dian ? ["Tipo y número de identificación del adquirente", "Resolución, prefijo y rango de numeración autorizado", "Fecha, hora, moneda y forma o medio de pago", "Detalle con código, cantidad, unidad de medida, descripción y valor", "Impuestos discriminados por tarifa, retenciones, descuentos y totales", "Generación del XML según anexo técnico aplicable", "Firma digital, CUFE o CUDE y código QR", "Transmisión y validación previa DIAN", "Entrega de XML y representación gráfica al adquirente", "Estados de envío, aceptación, rechazo y contingencia"] : []
  return <div className="space-y-5"><div><Button asChild variant="ghost" size="sm" className="mb-3"><Link href="/admin/movimientos"><ArrowLeft className="mr-2 h-4 w-4" />Volver a movimientos</Link></Button><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{module.name}</h1>{module.dian && <Badge className="bg-cyan-50 text-cyan-800" variant="secondary">{module.dian}</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{module.description}</p></div><Button><Settings2 className="mr-2 h-4 w-4" />Configurar submódulo</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info icon={FileCheck2} label="Estado" value={module.status} /><Info icon={Landmark} label="Contabilidad" value={module.effects.includes("Contabilidad") ? "Genera asiento" : "Sin afectación"} /><Info icon={PackageCheck} label="Inventario" value={module.effects.includes("Inventario") ? "Genera movimiento" : "Sin afectación"} /><Info icon={CircleDollarSign} label="Cartera / caja" value={module.effects.some((item) => item === "Cartera" || item === "Caja") ? "Integrado" : "No aplica"} /></div>
    <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><Card><CardContent className="p-5"><h2 className="font-semibold">Base funcional preparada</h2><p className="mt-1 text-sm text-muted-foreground">Este submódulo ya tiene definida su ruta, alcance y relaciones empresariales. La implementación detallada se construirá en la siguiente fase.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Encabezado y consecutivo del documento", "Tercero, identificación y datos de contacto", "Detalle de artículos, servicios o cuentas", "Impuestos, descuentos y totales", "Aprobaciones, estados y responsables", "Asiento contable y trazabilidad", "Anexos y observaciones", "Impresión, exportación y auditoría"].map((item) => <div key={item} className="flex gap-2 rounded-lg border p-3 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</div>)}</div></CardContent></Card><Card><CardContent className="p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" /><h2 className="font-semibold">{module.dian ? "Preparación DIAN" : "Controles del documento"}</h2></div><div className="mt-4 space-y-3">{(dianRequirements.length ? dianRequirements : ["Consecutivo único por tipo de documento", "Período contable abierto", "Usuario y trazabilidad de cambios", "Validación de débitos y créditos", "Permisos de creación, aprobación y anulación"]).map((item) => <div key={item} className="flex gap-2 text-xs leading-5"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</div>)}</div>{module.dian && <div className="mt-4 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900">La emisión real requerirá configurar facturador, modo de operación, certificado digital, software habilitado y rangos de numeración.</div>}</CardContent></Card></div>
  </div>
}

function Info({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <Card><CardContent className="flex items-center gap-3 p-4"><span className="rounded-xl bg-primary/10 p-2 text-primary"><Icon className="h-5 w-5" /></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm font-bold">{value}</p></div></CardContent></Card> }
